# This is a sample, non-production-ready template.
#
# © 2019 Amazon Web Services, In​c. or its affiliates. All Rights Reserved.
#
# This AWS Content is provided subject to the terms of the
# AWS Customer Agreement available at http://aws.amazon.com/agreement
# or other written agreement between Customer and either
# Amazon Web Services, Inc. or Amazon Web Services EMEA SARL or both.

AWSTemplateFormatVersion: "2010-09-09"
Description: S3 Backing Service

Parameters:

  ServiceBindings:
    Description: Comma-separated list for role names to add permissions to
    Type: String
    Default: ""

Resources:

  S3Bucket:
    Type: 'AWS::S3::Bucket'

  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      PolicyDocument:
        Id: Policy
        Version: 2012-10-17
        Statement:
          - Sid: ReadWriteFromApp
            Effect: Allow
            Principal:
              AWS: !Split
                - ','
                - !Sub
                  - '${ServiceBindingsList}'
                  - ServiceBindingsList: !Join [',', [ !Ref ServiceBindings ] ]
            Action:
              - 's3:GetObject'
              - 's3:PutObject'
            Resource: !Join [ '', [ 'arn:aws:s3:::', !Ref S3Bucket, '/*' ] ]
      Bucket: !Ref S3Bucket

Outputs:
  ServiceArn:
    Value: !GetAtt S3Bucket.Arn