AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation IAM Role for Pipeline Deployment

Parameters:

  DeploymentRoleName:
    Type: String
    Description: IAM Role Name for the deployment role CodePipeline assumes to exceute the CloudFormation Template.
    Default: cloudformation-deployment-role

  DelegationRoleName:
    Type: String
    Description: IAM Role Name for CodePipeline to delegate execution of the CloudFormation Template.
    Default: cloudformation-delegation-role

  DevAccountId:
    Type: String
    Description: (Optional) 12-digit AWS Account ID
    Default: ""

  TestAccountId:
    Type: String
    Description: (Optional) 12-digit AWS Account ID
    Default: ""

  ProdAccountId:
    Type: String
    Description: 12-digit AWS Account ID

Conditions:
  DevStageExist: !Not [!Equals ["", !Ref DevAccountId ]]
  TestStageExist: !Not [!Equals ["", !Ref TestAccountId ]]

Resources:

  KMSKey:
    Type: AWS::KMS::Key
    Properties:
      EnableKeyRotation: true
      KeyPolicy:
        Version: "2012-10-17"
        Id: pipeline-kms-key
        Statement:
          - Sid: Allows admin of the key
            Effect: Allow
            Principal:
              AWS: !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:root"
            Action: ["kms:*"]
            Resource: "*"
          - Sid: Allow use of the key from the other accounts
            Effect: Allow
            Principal:
              AWS:
                - !If
                  - DevStageExist
                  - !Sub arn:${AWS::Partition}:iam::${DevAccountId}:role/${DeploymentRoleName}
                  - !Ref AWS::NoValue
                - !If
                  - DevStageExist
                  - !Sub arn:${AWS::Partition}:iam::${DevAccountId}:role/${DelegationRoleName}
                  - !Ref AWS::NoValue
                - !If
                  - TestStageExist
                  - !Sub arn:${AWS::Partition}:iam::${TestAccountId}:role/${DeploymentRoleName}
                  - !Ref AWS::NoValue
                - !If
                  - TestStageExist
                  - !Sub arn:${AWS::Partition}:iam::${TestAccountId}:role/${DelegationRoleName}
                  - !Ref AWS::NoValue
                - !Sub arn:${AWS::Partition}:iam::${ProdAccountId}:role/${DeploymentRoleName}
                - !Sub arn:${AWS::Partition}:iam::${ProdAccountId}:role/${DelegationRoleName}
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: "*"

  KMSAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub alias/codepipeline-crossaccounts-${AWS::StackName}
      TargetKeyId: !Ref KMSKey

  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: BucketOwnerFullControl
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
    DeletionPolicy: Delete

  ArtifactBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ArtifactBucket
      PolicyDocument:
        Statement:
          - Action:
              - s3:Get*
              - s3:List*
              - s3:PutObject*
              - s3:PutReplicationConfiguration
            Effect: Allow
            Resource:
            - !Sub arn:${AWS::Partition}:s3:::${ArtifactBucket}
            - !Sub arn:${AWS::Partition}:s3:::${ArtifactBucket}/*
            Principal:
              AWS:
                - !If
                  - DevStageExist
                  - !Sub arn:${AWS::Partition}:iam::${DevAccountId}:role/${DeploymentRoleName}
                  - !Ref AWS::NoValue
                - !If
                  - DevStageExist
                  - !Sub arn:${AWS::Partition}:iam::${DevAccountId}:role/${DelegationRoleName}
                  - !Ref AWS::NoValue
                - !If
                  - TestStageExist
                  - !Sub arn:${AWS::Partition}:iam::${TestAccountId}:role/${DeploymentRoleName}
                  - !Ref AWS::NoValue
                - !If
                  - TestStageExist
                  - !Sub arn:${AWS::Partition}:iam::${TestAccountId}:role/${DelegationRoleName}
                  - !Ref AWS::NoValue
                - !Sub arn:${AWS::Partition}:iam::${ProdAccountId}:role/${DeploymentRoleName}
                - !Sub arn:${AWS::Partition}:iam::${ProdAccountId}:role/${DelegationRoleName}

Outputs:

  ArtifactBucket:
    Value: !Ref ArtifactBucket
    Export:
      Name: 'CodePipelineArtifactBucket'

  KMSArn:
    Value: !GetAtt KMSKey.Arn
    Export:
      Name: 'CodePipelineKMSArn'
